### PR TITLE
Add `setModifierManager` method export off of modifier

### PR DESCRIPTION
**Pull request by jordpo**
I messed up the ordering. Small fix here.

### CODE REVIEW

**Comment by jordpo** [comment]
No idea what is happening but there is only one entry locally and when I view the file here. I fetched and merged from upstream and rebased my branch off of that but still seeing this wonky diff.

**Comment by rwjblue** [comment]
Woah, so odd 🤔

**Comment by jordpo** [comment]
Want me to just close this?

**Comment by rwjblue** [comment]
Ya, sorry about the trouble.

**Pull request closed without merging**
