### PR TITLE
Support "import { Promise } from 'rsvp';"

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves part of #13 

```js
import { Promise } from 'rsvp';
```

instead of

```js
import RSVP from 'rsvp';

const { Promise } = RSVP;
```

/cc @cibernox @stefanpenner

### CODE REVIEW

**Comment by rwjblue** [comment]
FWIW, we discussed this at the ember core team meeting yesterday and @tomdale clarified that in his original RFC what he intended by `import RSVP from 'rsvp';` was that the `rsvp` module would support the standard public API of RSVP. 

According to [the source](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp.js#L73-L94) this would essentially allow:

```js
import {
  asap,
  cast,
  Promise,
  EventTarget,
  all,
  allSettled,
  race,
  hash,
  hashSettled,
  rethrow,
  defer,
  denodeify,
  configure,
  on,
  off,
  resolve,
  reject,
  map,
  async,
  filter
} from 'rsvp';
```

Though we may want to exclude _some_ of those though...

**Comment by Turbo87** [comment]
@rwjblue I'm now wondering if this import path was correct... according to the conventions it probably should have been `import Promise from 'rsvp/promise';`, but do those conventions apply to RSVP too?

**Comment by rwjblue** [comment]
Hmm. Good point.  I think the general idea is to support whatever RSVP's API is from our rsvp module. Can you do `require('rsvp/promise')` today?

**Comment by Turbo87** [comment]
I don't think so. AFAIK the public API is using everything from `require('rsvp')`.

**Comment by tomdale** [comment]
I agree with @rwjblue here: we should try to reduce the API surface area of Ember by exposing dependencies as-is, rather than providing our own module API on top.

A good litmus test for this is: can I take `import`s and associated code from a webpack app that uses RSVP and copy and paste it into an Ember app and have it work? If yes, then I think we're #winning.

**Pull request merged**
