### PR TITLE
[FEATURE] Move htmlSafe and isHTMLSafe to @ember/component

### PR DESCRIPTION
**Pull request by Serabe**
Related to emberjs/rfcs#236.

Task in emberjs/ember.js#15624

### CODE REVIEW

**Comment by Turbo87** [comment]
We can't do this. This is a breaking change!

**Comment by Serabe** [comment]
With current format, there cannot be two shims for the same function. Shall I change the format?

**Comment by Turbo87** [comment]
Changing the format is also a breaking change.

**Comment by locks** [comment]
Is this project not on v0.2.7?

**Comment by Turbo87** [comment]
v0.2.7 of what?  I don't understand the question

**Comment by martletandco** [comment]
How does this impact [helpers](https://guides.emberjs.com/v2.6.0/templates/writing-helpers/#toc_escaping-html-content)? `htmlSafe` and friends fall under templates rather than just components. You can import @ember/component into a helper but that shows it's a little off

**Comment by Serabe** [comment]
Hello @martletandco:

That's an interesting point. Can you repeat it in https://github.com/emberjs/rfcs/pull/236 ? I think it is worth it :)

Thank you!

**Comment by rwjblue** [comment]
> We can't do this. This is a breaking change!

Sure we can, we just need a major version bump here.

**Comment by rwjblue** [comment]
IMHO, the current JSON format needs a bit of reworking to accommodate multiple import paths pointing to a single global. We should focus on deciding what the new format is, so that the underlying work can begin.

**Comment by rwjblue** [comment]
My suggestion:

```json
[
  { 
    "global": "Ember.String.isHTMLSafe", 
    "module": "@ember/component", 
    "export": "isHTMLSafe", 
    "deprecated": true,
    "replacement": { "module": "@ember/template", "export": "isHTMLSafe" }
  },
  { 
    "global": "Ember.String.isHTMLSafe", 
    "module": "@ember/template", 
    "export": "isHTMLSafe", 
    "deprecated": false
  },
  { 
    "global": "Ember.Component", 
    "module": "ember-component", 
    "export": "default", 
    "deprecated": true,
    "replacement": { "module": "@ember/component", "export": "default" }
  },
  { 
    "global": "Ember.Component", 
    "module": "@ember/component", 
    "export": "default", 
    "deprecated": false
  }
]
```

**Comment by locks** [comment]
I believe #38 supersedes this one.

**Pull request closed without merging**
