### PR TITLE
New mappings structure

### PR DESCRIPTION
**Pull request by Turbo87**
This PR converts the mappings to the new structure proposed in https://github.com/ember-cli/ember-rfc176-data/pull/36#issuecomment-330222314

We should only merge this once we've verified that the three main projects using this package can work with the new structure.

/cc @serabe @locks

### CODE REVIEW

**Comment by rwjblue** [comment]
> We should only merge this once we've verified that the three main projects using this package can work with the new structure.

You mean to confirm that it should be possible? Or that the work is actually done? The reason I am clarifying is that it is _somewhat_ annoying to have to do the development with everything locally linked. In other words, I'm hoping that you mean to confirm that the individual project requirements can be satisfied by the new format...

**Comment by Serabe** [comment]
@rwjblue the same information is still there.

For named exports:

```js
// Old format
{
  // Some other fields
  "computed.gt": ["@ember/object/computed", "gt"]
}

// New format

[
  // Some other objects
  {
     "global": "Ember.computed.gt", // same as `Ember.${keyOldFormat}`
     "module": "@ember/object/computed", // same as valueOldFormat[0]
     "export": "gt", // same as valueOldFormat[1]
     "deprecated": false // no option in old format
  },
]
```

For default exports:

```js
// Old format

{
  // Some other fields
  "Router": ["@ember/routing/router", null, "EmberRouter"],
}

// New format

[
  {
    "global": "Ember.Router", // same as `Ember.${keyOldFormat}`
    "module": "@ember/routing/router", // same as valueOldFormat[0]
    "export": "default",
    "localName": "EmberRouter", // same as valueOldFormat[2]
    "deprecated": false
  },
]
```

Which are all the projects depending on this one? I'm working on updating the babel plugin, so I can work on the others too.

**Comment by Serabe** [comment]
@Turbo87 can change `main` in `package.json` to point to the new mapping file?

**Comment by rwjblue** [comment]
Getting the list from [npmjs.com](https://www.npmjs.com/browse/depended/ember-rfc176-data):

* `babel-plugin-ember-modules-api-polyfill`
* `ember-modules-codemod`
* `eslint-plugin-ember`

**Comment by Serabe** [comment]
@Turbo87 great work!

**Comment by Serabe** [comment]
PRs done:

- https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/27
- https://github.com/ember-cli/ember-modules-codemod/pull/42
- https://github.com/ember-cli/eslint-plugin-ember/pull/142

All PRs bump version for `ember-rfc176-data` to `^0.3.0` (though I'm not a fan of ^, it was what it was) and assume `main` gets changed to the new json file. After this has been accepted, I'll just need to `yarn` to fix the `yarn.lock` files and that should be all.

Thank you!

**Comment by rwjblue** [comment]
After chatting with @Serabe in slack and in https://github.com/ember-cli/eslint-plugin-ember/pull/142, it seems that we have lost some of the old shims in this conversion.  For example, I do not see `ember-controller/sortable` in the new file, but I would expect it to be:

```js
{ 
  global: 'Ember.Sortable', 
  module: 'ember-controller/sortable', 
  export: 'default', 
  deprecated: true 
}
```

**Comment by Turbo87** [comment]
@rwjblue I've added the missing entries from the old shims now

**Comment by Serabe** [comment]
Updated all three PRs

**Comment by rwjblue** [comment]
Just to be clear amongst us, we should make a few changes:

*  `deprecated` to either be a boolean or a string (which is a valid `semver` range).  I don't believe that it really matters just yet (all of the current deprecated items are deprecated unrelated to specific versions), but it will matter for things like `import { isHTMLSafe } from '@ember/string'` which we plan to move from pointing to `Ember.String.isHTMLSafe` to `Ember.Template.isHTMLSafe` (and `import { isHTMLSafe } from '@ember/template'`).
* add an optional `since` field which is a semver range indicating when the import is valid from. Again, this isn't a blocker or anything, just a nice-to-have in the format for future use as new imports are made available to new versions.

**Comment by Serabe** [comment]
What do we need to merge this and make a new release?

**Comment by rwjblue** [comment]
Released as v0.3.0.

**Pull request merged**
