### PR TITLE
[WIP] Add "generate-typings" script

### PR DESCRIPTION
**Pull request by vlascik**
Add a script to generate Typescript ambient modules to enable import completion for the new API.

See discussion at https://github.com/Turbo87/intellij-emberjs/issues/151 for more detail.

WIP, needs to be checked for correctness etc. (everything is exported either as a class or a function, not sure if that's correct), but should work.

Generated `ember.d.ts` here: https://gist.github.com/vlascik/678b7163f2cd62241b3ede0a0fe66c87

### CODE REVIEW

**Comment by Turbo87** [comment]
@vlascik I'm not sure that this will work that well. for example `export function computed() {}` will defined a `computed` function, but without any parameters. if you use that function from TypeScript it would complain that you are passing parameters into it that it didn't expect.

/cc @chriskrycho @locks

**Comment by chriskrycho** [comment]
Yeah, alas, the *best* this could do would be give us a baseline for anything which actually changed in terms of the module APIs. The vast majority of the types would actually be pretty seriously wrong. For an easy example: `Component` should extend from `Ember.Object`, but doesn't, and it has no properties on it, and so on.

While I'm *very* interested in generating typings automatically, my *very strong* impression is that the ES6 class API (as opposed to the `Ember.Object.extend()` custom class model) needs to land for it to even be remotely possible.

**Comment by vlascik** [comment]
Of course this is a temporary kludge, however, at least now I don't have to remember all imports or check the readme here all the time, so I thought I'd share it. Generated file is out there, maybe it will help someone.

Is there some sort of a timeline for ES6 and new modules to land or an issue that tracks a progress on this?

**Comment by chriskrycho** [comment]
I can't speak to the timeline, but I can say re:TypeScript—the better solution would be to help get the type definitions at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember/index.d.ts) written in such a way as to support it. You can drop into the `#topic-typescript` room in the Ember Community Slack and I and others will happily comment on what it'll take to manage that. It *should* be possible for both module systems to live in parallel with each other in DefinitelyTyped; initially the `@ember/application` module can simply re-export what's in the other module, and over time we'll continue the migration.

**Comment by Turbo87** [comment]
as I tend to agree with @chriskrycho here I'll close this PR in favor of getting the semi-official typings to a better state

**Comment by vlascik** [comment]
@Turbo87 output of this script probably will become a part of semi-official typings, maybe it would be better if it was somewhere? typings maintainers might need to run it regularly to update the exports.

**Comment by chriskrycho** [comment]
Actually, we really shouldn't. It is a good thought, but this kind of large scale change to the API should be extremely rare.

**Comment by vlascik** [comment]
My point is that this repo is still in flux, things are being fixed, added and removed every other day.

**Comment by Turbo87** [comment]
@vlascik feel free to put the generator in a separate project and depend on this one here :)

**Comment by vlascik** [comment]
Seems like way too much hassle for something that's basically a copy of a script from here with a bunch of methods changed :) 
I will keep it in my fork, use it or don't, new module imports work for me, I'm not going to bother with it much further.

**Pull request closed without merging**
